Src/Dft.DTRO.Admin/Models/DtroHistory/DtroHistoryProvisionResponse.cs
namespace Dft.DTRO.Admin.Models.DtroHistory;

public class DtroHistoryProvisionResponse
{
    public string ActionType { get; set; }

    public DateTime? Created { get; set; }

    public ExpandoObject Data { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string Reference { get; set; }

    public string SchemaVersion { get; set; }
}

Src/Dft.DTRO.Admin/Models/DtroHistory/DtroHistorySourceResponse.cs
namespace Dft.DTRO.Admin.Models.DtroHistory;
public class DtroHistorySourceResponse
{
    public string ActionType { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string Reference { get; set; }

    public string SchemaVersion { get; set; }

    public string Section { get; set; }

    public int TrafficAuthorityCreatorId { get; set; }

    public int TrafficAuthorityOwnerId { get; set; }

    public string TroName { get; set; }
}

Src/Dft.DTRO.Admin/Models/Metrics/FullMetric.cs
namespace Dft.DTRO.Admin.Models.Metrics;

public class FullMetricSummary
{
    [DataMember(Name = "forDate")]
    public string ForDate { get; set; }

    [DataMember(Name = "userName")]
    public string UserName { get; set; } = string.Empty;

    [DataMember(Name = "systemFailureCount")]
    public int SystemFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionFailureCount")]
    public int SubmissionFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionCount")]
    public int SubmissionCount { get; set; } = 0;

    [DataMember(Name = "deletionCount")]
    public int DeletionCount { get; set; } = 0;

    [DataMember(Name = "searchCount")]
    public int SearchCount { get; set; } = 0;

    [DataMember(Name = "eventCount")]
    public int EventCount { get; set; } = 0;
}

Src/Dft.DTRO.Admin/Models/Metrics/MetricRequest.cs
namespace Dft.DTRO.Admin.Models.Metrics;


[DataContract]
public class MetricRequest
{
    [DataMember(Name = "dtroUserId")]
    public Guid? DtroUserId { get; set; }

    [DataMember(Name = "dateFrom")]
    public DateTime DateFrom { get; set; }

    [DataMember(Name = "dateTo")]
    public DateTime DateTo { get; set; }

    [DataMember(Name = "userGroup")]
    public UserGroup UserGroup { get; set; }
}

Src/Dft.DTRO.Admin/Models/Metrics/MetricSummary.cs
namespace Dft.DTRO.Admin.Models.Metrics;

public class MetricSummary
{
    [DataMember(Name = "systemFailureCount")]
    public int SystemFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionFailureCount")]
    public int SubmissionFailureCount { get; set; } = 0;

    [DataMember(Name = "submissionCount")]
    public int SubmissionCount { get; set; } = 0;

    [DataMember(Name = "deletionCount")]
    public int DeletionCount { get; set; } = 0;

    [DataMember(Name = "searchCount")]
    public int SearchCount { get; set; } = 0;

    [DataMember(Name = "eventCount")]
    public int EventCount { get; set; } = 0;
}

Src/Dft.DTRO.Admin/Models/Search/BoundingBox.cs
namespace Dft.DTRO.Admin.Models.Search;

public record struct BoundingBox(double westLongitude, double southLatitude, double eastLongitude, double northLatitude)
{
    public static readonly BoundingBox ForOsgb36Epsg27700 = new(-103976.3, -16703.87, 652897.98, 1199851.44);

    public static readonly BoundingBox ForWgs84Epsg4326 = new(-7.5600, 49.9600, 1.7800, 60.8400);
}

Src/Dft.DTRO.Admin/Models/Search/ComparisonOperator.cs
namespace Dft.DTRO.Admin.Models.Search;

[DataContract]
public enum ComparisonOperator
{
    [EnumMember(Value = "=")]
    Equal,

    [EnumMember(Value = ">")]
    GreaterThan,

    [EnumMember(Value = ">=")]
    GreaterThanOrEqual,

    [EnumMember(Value = "<")]
    LessThan,

    [EnumMember(Value = "<=")]
    LessThanOrEqual
}

Src/Dft.DTRO.Admin/Models/Search/DtroSearch.cs
namespace Dft.DTRO.Admin.Models.Search;

public class DtroSearch : PaginatedRequest
{
    [MinLength(1)]
    public IEnumerable<SearchQuery> Queries { get; set; }
}

Src/Dft.DTRO.Admin/Models/Search/DtroSearchResult.cs
namespace Dft.DTRO.Admin.Models.Search;

[DataContract]
public class DtroSearchResult
{
    [DataMember(Name = "troName")]
    public string TroName { get; set; }

    [DataMember(Name = "publicationTime")]
    public DateTime PublicationTime { get; set; }

    [DataMember(Name = "trafficAuthorityCreatorId")]
    public long TrafficAuthorityCreatorId { get; set; }

    [DataMember(Name = "trafficAuthorityOwnerId")]
    public long TrafficAuthorityOwnerId { get; set; }

    [DataMember(Name = "regulationType")]
    public IEnumerable<string> RegulationType { get; set; }

    [DataMember(Name = "vehicleType")]
    public IEnumerable<string> VehicleType { get; set; }

    [DataMember(Name = "orderReportingPoint")]
    public IEnumerable<string> OrderReportingPoint { get; set; }

    [DataMember(Name = "regulationStart")]
    public IEnumerable<DateTime> RegulationStart { get; set; }

    [DataMember(Name = "regulationEnd")]
    public IEnumerable<DateTime> RegulationEnd { get; set; }

    [DataMember(Name = "Id")]
    public Guid Id { get; set; }
}

Src/Dft.DTRO.Admin/Models/Search/Location.cs
namespace Dft.DTRO.Admin.Models.Search;

public class Location
{
    [Required]
    [RegularExpression(
        "^(?:osgb36Epsg27700|wgs84Epsg4326)$",
        ErrorMessage = "Value must be one of 'osgb36Epsg27700' and 'wgs84Epsg4326'.")]
    public string Crs { get; set; }

    [Required]
    public BoundingBox Bbox { get; set; }
}

Src/Dft.DTRO.Admin/Models/Search/PaginatedRequest.cs
namespace Dft.DTRO.Admin.Models.Search;

public class PaginatedRequest
{
    [Range(1, int.MaxValue)]
    [Required]
    public int Page { get; set; }

    [Range(1, 50)]
    [Required]
    public int PageSize { get; set; }
}

Src/Dft.DTRO.Admin/Pages/DtroDropEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroDropEditModel : PageModel
{
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;
    public DtroDropEditModel(IDtroService dtroService, IConfiguration configuration, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public string Id { get; set; }

    public async Task<IActionResult> OnPostAsync(IFormFile file, bool isEdit, string id)
    {
        try
        {
            if (isEdit)
            {
                await _dtroService.UpdateDtroAsync(Guid.Parse(id), file);
            }
            else
            {
                await _dtroService.CreateDtroAsync(file);
            }

            return RedirectToPage("Search");
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroEditModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;
    [BindProperty(SupportsGet = true)]
    public DtroUserSearch DtroUserSearch { get; set; } = new DtroUserSearch();

    [BindProperty(SupportsGet = true)]
    public string Id { get; set; }

    public DtroEditModel(IDtroService dtroService, IDtroUserService traService, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _dtroUserService = traService;
        _errHandlingService = errHandlingService;
    }

    public async Task OnGetAsync()
    {
        DtroUserSearch.AlwaysButtonHidden = true;
        DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();
        DtroUserSearch.DtroUsers.RemoveAll(x => x.UserGroup != UserGroup.Tra);
    }


    public async Task<IActionResult> OnPostAsync(Guid id)
    {
        try
        {
            if (TempData.TryGetValue("DtroUserSelect", out object dtroUserSelect))
            {
                DtroUserSearch.DtroUserIdSelect = (Guid)dtroUserSelect;
            }

            if (DtroUserSearch.DtroUserIdSelect != null)
            {
                await _dtroService.ReassignDtroAsync(id, DtroUserSearch.DtroUserIdSelect.Value);

            }

            return RedirectToPage("Search");
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroHistory.cshtml.cs
namespace Dft.DTRO.Admin.Pages;

public class DtroHistoryModel : PageModel
{
    private readonly IDtroService _dtroService;
    private readonly IErrHandlingService _errHandlingService;

    [BindProperty(SupportsGet = true)]
    public Guid Id { get; set; }

    [BindProperty(SupportsGet = true)]
    public List<DtroHistoryProvisionResponse> ProvisionHistory { get; set; }

    [BindProperty(SupportsGet = true)]
    public List<DtroHistorySourceResponse> SourceHistory { get; set; }


    public DtroHistoryModel(IDtroService dtroService, IErrHandlingService errHandlingService)
    {
        _dtroService = dtroService;
        _errHandlingService = errHandlingService;
    }

    public async Task<IActionResult> OnGetAsync()
    {


        try
        {
            SourceHistory = await _dtroService.DtroSourceHistory(Id);
            ProvisionHistory = await _dtroService.DtroProvisionHistory(Id);
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

}

Src/Dft.DTRO.Admin/Pages/DtroUserDelete.cshtml.cs
namespace Dft.DTRO.Admin.Pages
{
    public class DtroUserDeleteModel : PageModel
    {
        private readonly IDtroUserService _dtroUserService;
        private readonly IErrHandlingService _errHandlingService;

        public DtroUserDeleteModel(IDtroUserService dtroUserService, IErrHandlingService errHandlingService)
        {
            _dtroUserService = dtroUserService;
            _errHandlingService = errHandlingService;
        }

        public List<DtroUser> AllDtroUsers { get; set; }

        [BindProperty]
        public List<Guid> SelectedUsers { get; set; }

        public async Task OnGet()
        {
            AllDtroUsers = (await _dtroUserService.GetDtroUsersAsync())
                .OrderBy(user => user.UserGroup)
                .ThenBy(user => user.Name)
                .ThenBy(user => user.xAppId)
                .ToList();
        }

        public async Task<IActionResult> OnPost(string action)
        {
            if (action == "delete")
            {
                try
                {
                    bool isUserDeleted = await _dtroUserService.DeleteDtroUserAsync(SelectedUsers);
                    return isUserDeleted ? RedirectToPage() : RedirectToPage("Error");
                }
                catch (Exception ex)
                {
                    return _errHandlingService.HandleUiError(ex);
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "No users selected for deletion.");
            }

            return RedirectToPage("Index");
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroUserEdit.cshtml.cs
namespace Dft.DTRO.Admin.Pages;
public class DtroUserEditModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly ISystemConfigService _systemConfigService;
    private readonly IErrHandlingService _errHandlingService;

    public DtroUserEditModel(IDtroUserService dtroUserService, ISystemConfigService systemConfigService, IErrHandlingService errHandlingService)
    {
        _systemConfigService = systemConfigService;
        _dtroUserService = dtroUserService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public Guid? DtroUserId { get; set; }

    [BindProperty(SupportsGet = true)]
    public bool IsEdit { get; set; }

    [BindProperty(SupportsGet = true)]
    public bool IsTestSystem { get; set; }

    [BindProperty]
    public DtroUser DtroUser { get; set; }

    [BindProperty(SupportsGet = true)]
    public string Search { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        try
        {
            var systemConfig = await _systemConfigService.GetSystemConfig();
            IsTestSystem = systemConfig.IsTest;

            if (IsEdit)
            {
                DtroUser = await _dtroUserService.GetDtroUserAsync(DtroUserId.Value);
            }
            else
            {
                DtroUser = new DtroUser();
            }
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public async Task<IActionResult> OnPostAsync()
    {
        try
        {
            var action = Request.Form["action"];
            if (action == "Cancel")
            {
                return RedirectToPage("DtroUserList", new { search = Search });
            }

            if (IsEdit)
            {
                DtroUser.Id = DtroUserId.Value;
                await _dtroUserService.UpdateDtroUserAsync(DtroUser);
            }
            else
            {
                await _dtroUserService.CreateDtroUserAsync(DtroUser);
                Search = DtroUser.Name;
            }

            return RedirectToPage("DtroUserList", new { search = Search });
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }
}

Src/Dft.DTRO.Admin/Pages/DtroUserList.cshtml.cs
namespace Dft.DTRO.Admin.Pages;

public class DtroUserListModel : PageModel
{
    private readonly IDtroUserService _dtroUserService;
    private readonly IErrHandlingService _errHandlingService;

    public DtroUserListModel(IDtroUserService dtroUserService, IErrHandlingService errHandlingService)
    {
        _dtroUserService = dtroUserService;
        _errHandlingService = errHandlingService;
    }

    [BindProperty(SupportsGet = true)]
    public DtroUserSearch DtroUserSearch { get; set; } = new DtroUserSearch();
    public List<DtroUser> FilteredDtroUsers { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        try
        {
            DtroUserSearch.AlwaysButtonEnabled = true;
            if (DtroUserSearch.Search != "" && DtroUserSearch.PreviousSearch == "")
            {
                DtroUserSearch.PreviousSearch = DtroUserSearch.Search;
            }

            DtroUserSearch.UpdateButtonText = "List";
            DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();

            if (DtroUserSearch.DtroUserIdSelect != null && DtroUserSearch.DtroUserIdSelect != Guid.Empty)
            {
                FilteredDtroUsers = DtroUserSearch.DtroUsers.Where(s => s.Id == DtroUserSearch.DtroUserIdSelect).ToList();
            }
            else
            {
                if (!string.IsNullOrWhiteSpace(DtroUserSearch?.Search))
                {
                    FilteredDtroUsers = await _dtroUserService.SearchDtroUsersAsync(DtroUserSearch.Search);
                }
                else
                {
                    FilteredDtroUsers = new List<DtroUser>();
                }
            }
            return Page();
        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public async Task<IActionResult> OnPostUpdate()
    {
        try
        {
            OnGetAsync().Wait();
            var action = Request.Form["action"];

            if (Guid.TryParse(action, out Guid dtroUserId))
            {
                if (dtroUserId != Guid.Empty)
                {
                    DtroUserSearch.DtroUsers = await _dtroUserService.GetDtroUsersAsync();
                    var dtroUser = DtroUserSearch.DtroUsers.Find(s => s.Id == dtroUserId);
                    if (dtroUser == null) return NotFound();

                    //To 
                    await _dtroUserService.DeactivateDtroUserAsync(dtroUserId);
                    await _dtroUserService.ActivateDtroUserAsync(dtroUserId);
                }
                DtroUserSearch.Search = DtroUserSearch.PreviousSearch;
                DtroUserSearch.DtroUserIdSelect = DtroUserSearch.PreviousDtroUserIdSelect;
            }
            else
            {
                if (DtroUserSearch.PreviousSearch != "" && DtroUserSearch.Search == null)
                {
                    DtroUserSearch.Search = DtroUserSearch.PreviousSearch;
                }
                else
                {
                    DtroUserSearch.PreviousSearch = DtroUserSearch.Search;
                }

                DtroUserSearch.PreviousDtroUserIdSelect = DtroUserSearch.DtroUserIdSelect;
            }
            return RedirectToPage(new { DtroUserSearch.Search, DtroUserSearch.DtroUserIdSelect, DtroUserSearch.PreviousDtroUserIdSelect, DtroUserSearch.PreviousSearch });

        }
        catch (Exception ex)
        {
            return _errHandlingService.HandleUiError(ex);
        }
    }

    public IActionResult OnGetRefresh()
    {
        return RedirectToPage(new { DtroUserSearch.DtroUserIdSelect });
    }

    public string FormatListToSingle(IEnumerable<string> items)
    {
        var formattedItems = new List<string>();
        foreach (var item in items)
        {
            string formattedItem = Regex.Replace(item, "(?<!^)([A-Z])", " $1");
            formattedItem = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(formattedItem.ToLower());
            formattedItems.Add(formattedItem);
        }
        return string.Join(", ", formattedItems);
    }
}

Src/Dft.DTRO.Admin/Pages/DtroEdit.cshtml
@page
@model DtroEditModel
@{
    string id = Request.Query["id"];
}

<h2>Assign Dtro</h2>


<form id="searchSection" method="post" enctype="multipart/form-data"  asp-page-handler="Post" style="display: flex;margin-top:20px;">
    <input type="hidden" name="id" value="@id" />

    <div>
        @await Html.PartialAsync("_TraSearchPartial", Model.DtroUserSearch)
    </div>
</form>

Src/Dft.DTRO.Admin/Pages/DtroUserList.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model DtroUserListModel

<h2>Users <a class="btn btn-primary" asp-page="DtroUserEdit" asp-route-IsEdit="false">+</a></h2>

<form id="searchSection" method="post" asp-page-handler="Update" style=" margin-top: 30px;margin-right: 20px;margin-bottom: 20px;">
    <div>
        @await Html.PartialAsync("_TraSearchPartial", Model.DtroUserSearch)
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>x-App-Id</th>
                <th>Group</th>
                <th>TRA Id</th>
                <th>Prefix</th>
                <th>Name</th>
                <th>Active</th>
                <th>Admin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var dtroUser in Model.FilteredDtroUsers)
            {
                <tr>
                    <td>@(dtroUser.xAppId == Guid.Empty ? "(Not Set)" : dtroUser.xAppId.ToString())</td>
                    <td>@dtroUser.UserGroup.ToString()</td>
                    <td>@dtroUser.TraId</td>
                    <td>@dtroUser.Prefix</td>
                    <td>@dtroUser.Name</td>
                    <td>
                        @if (dtroUser.xAppId != Guid.Empty)
                        {
                            <img src="@Url.Content("~/images/tick.png")" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/images/cross.png")" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        @if (dtroUser.UserGroup == UserGroup.Admin)
                        {
                            <img src="@Url.Content("~/images/tick.png")" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/images/cross.png")" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        <a class="btn btn-info" asp-page="DtroUserEdit" asp-route-IsEdit="true" asp-route-search="@Model.DtroUserSearch.PreviousSearch" asp-route-dtroUserId="@dtroUser.Id">Edit</a>
                       
                        
                     @*    <button type="submit" 
                            name="action" 
                            value= "@dtroUser.TraId"
                            class="btn btn-@(dtroUser.IsActive ? "warning" : "success")" 
                            style="min-width: 100px;">
                                @(dtroUser.IsActive ? "Disable" : "Enable")
                            </button> *@
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

Src/Dft.DTRO.Admin/Pages/Search.cshtml
@page
@model SearchModel

<h2>
    DTROs - Total found: @Model.Dtros.TotalCount
    @if (Model.AllowAddUpdate)
    {
        <a class="btn btn-primary" asp-page="DtroDropEdit" asp-route-IsEdit="false">+</a>
    }
</h2>

<form id="searchSection" method="post" asp-page-handler="Update" style="display: flex; margin-top:20px;">
    <div>
        @await Html.PartialAsync("_TraSearchPartial", Model.DtroUserSearch)
    </div>
</form>

<table style="margin-top:30px" class="table">
    <thead>
        <tr>
            <th>Tro Name</th>
            <th>Published</th>
            <th>Regulation</th>
            <th>Vehicle</th>
            <th>DTRO Type</th>
            <th>Period</th>
            <th>File</th>
            <th>Creator</th>
            <th>Owner</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var result in Model.Dtros.Results)
        {
            <tr>
                <td>@result.TroName</td>
                <td>@result.PublicationTime</td>
                <td>@Model.FormatListToSingle(result.RegulationType)</td>
                <td>@Model.FormatListToSingle(result.VehicleType)</td>
                <td>@Model.FormatListToSingle(result.OrderReportingPoint)</td>
                <td>
                    @for (int i = 0; i < result.RegulationStart.Count(); i++)
                    {
                        <div>
                            <strong>Start:</strong> @result.RegulationStart.ElementAt(i) <br />
                            <strong>End:</strong> @result.RegulationEnd.ElementAt(i)
                        </div>
                    }
                </td>
                <td>
                    @if (Model.AllowAddUpdate)
                    {
                        <a class="btn btn-primary" asp-page="DtroDropEdit" asp-route-IsEdit="true" asp-route-id="@result.Id">Upload</a>
                    }
                </td>
                <td>@result.TrafficAuthorityCreatorId</td>
                <td>@result.TrafficAuthorityOwnerId</td>
                <td>
                    <a class="btn btn-primary" asp-page="DtroEdit" asp-route-id="@result.Id">Reassign</a>
                </td>
                <td>
                    <a class="btn btn-info" asp-page="DtroHistory" asp-route-id="@result.Id">History</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    const int maxPageSize = 50;
    var totalPages = (int)Math.Ceiling((double)Model.Dtros.TotalCount / maxPageSize);
    const int displayPages = 2;
}

<div style="display: flex; justify-content: space-between; margin-top: 20px;">
    <div>
        @if (Model.Dtros.TotalCount > 0)
        { 
            var startRecord = (Model.Dtros.Page - 1) * maxPageSize + 1;
            var endRecord = Math.Min(Model.Dtros.Page * maxPageSize, Model.Dtros.TotalCount);
            <span>@startRecord - @endRecord of @Model.Dtros.TotalCount</span>
        }
    </div>
    <!-- Pages Controls -->
    <div>
        @if (Model.Dtros.TotalCount > Model.Dtros.PageSize)
        {
            <nav aria-label="tro navigation">
                <ul class="pagination justify-content-end">
                    @if (Model.Dtros.Page > 1)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-page-handler="Update" asp-route-pageNumber="@(Model.Dtros.Page - 1)" asp-route-dtroUserIdSelect="@Model.DtroUserSearch.DtroUserIdSelect">Previous</a>
                        </li>
                    }

                    @if (Model.Dtros.Page > displayPages + 1)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-page-handler="Update" asp-route-pageNumber="1">1</a>
                        </li>
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                    }

                    @for (int i = Math.Max(1, Model.Dtros.Page - displayPages); i <= Math.Min(totalPages, Model.Dtros.Page + displayPages); i++)
                    {
                        <li class="page-item @(i == Model.Dtros.Page ? "active" : "")">
                            <a class="page-link" asp-page-handler="Update" asp-route-pageNumber="@i" asp-route-dtroUserIdSelect="@Model.DtroUserSearch.DtroUserIdSelect">@i</a>
                        </li>
                    }

                    @if (Model.Dtros.Page < totalPages - displayPages)
                    {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                        <li class="page-item">
                            <a class="page-link" asp-page-handler="Update" asp-route-pageNumber="@totalPages">@totalPages</a>
                        </li>
                    }
                    @if (Model.Dtros.Page < totalPages)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-page-handler="Update" asp-route-pageNumber="@(Model.Dtros.Page + 1)" asp-route-dtroUserIdSelect="@Model.DtroUserSearch.DtroUserIdSelect">Next</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>
</div>

Src/Dft.DTRO.Admin/Pages/TraList.cshtml
@page
@model TraListModel

<h2>TRAs <a class="btn btn-primary" asp-page="TraEdit" asp-route-IsEdit="false">+</a></h2>

@* <input  style="color: palegoldenrod" name="TraSearch.PreviousSearch" value="@Model.TraSearch.PreviousSearch" /> *@


<form id="searchSection" method="post" asp-page-handler="Update" style=" margin-top: 30px;margin-right: 20px;margin-bottom: 20px;">
    <div>
        @await Html.PartialAsync("_TraSearchPartial", Model.TraSearch)
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>TRA Id</th>
                <th>Prefix</th>
                <th>Name</th>
                <th>Active</th>
                <th>Admin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var swa in Model.FilteredSwaCodes)
            {
                <tr>
                    <td>@swa.TraId</td>
                    <td>@swa.Prefix</td>
                    <td>@swa.Name</td>
                    <td>
                        @if (swa.IsActive)
                        {
                            <img src="~/images/tick.png" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="~/images/cross.png" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        @if (swa.IsAdmin)
                        {
                            <img src="~/images/tick.png" alt="Active" style="max-height:20px; vertical-align: middle;" />
                        }
                        else
                        {
                            <img src="~/images/cross.png" alt="Inactive" style="max-height:20px; vertical-align: middle;" />
                        }
                    </td>
                    <td>
                        <a class="btn btn-info" asp-page="TraEdit" asp-route-IsEdit="true" asp-route-search="@Model.TraSearch.PreviousSearch" asp-route-traId="@swa.TraId">Edit</a>
                       
                        
                        <button type="submit" 
                            name="action" 
                            value= "@swa.TraId"
                            class="btn btn-@(swa.IsActive ? "warning" : "success")" 
                            style="min-width: 100px;">
                                @(swa.IsActive ? "Disable" : "Enable")
                            </button>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>